# Generated by Django 3.1.3 on 2021-07-21 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Warehouse_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Release_Date_mw', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('RFID_Number_mwout', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity_mwout', models.IntegerField(blank=True, default=0, null=True)),
                ('Location_mw', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
