# Generated by Django 3.1.3 on 2021-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_auto_20210702_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_product_warehouse',
            name='Quantity_fw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
