# Generated by Django 3.1.3 on 2021-07-05 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_auto_20210702_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_warehouse',
            name='Receiving_Date_mw',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='material_warehouse',
            name='Release_Date_mw',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
