# Generated by Django 3.1.3 on 2021-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_auto_20210705_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_warehouse',
            name='Quantity_mw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
