# Generated by Django 3.1.3 on 2021-07-08 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0007_auto_20210706_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('RFID_Number_dr', models.CharField(blank=True, max_length=50, null=True)),
                ('Gate_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Direction', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
