from django.urls import path

from . import views

app_name = 'rfid'

urlpatterns = [
    path('mw/', views.index, name='index'),
    path('pl/', views.proline, name='proline'),
    path('fpw/', views.fpware, name='fpware'),
    path('rest/test', views.test),
    path('rest/', views.material_list),
    path('rest2/', views.production_list),
    path('rest3/', views.finished_list),
    path('rule/', views.rule),
    path('visual/', views.visual),
    path('direction/', views.direction, name='dir'),
    path('rest4/', views.direction_list),
    path('main/', views.main, name='main'),
    path('rule1/', views.rule1, name='rule1'),
    path('rule2/', views.rule2, name='rule2'),
    path('rule3/', views.rule3, name='rule3'),
    path('rule4/', views.rule4, name='rule4'),
    path('pl/<int:production_id>/', views.edit_pl, name='pl_edit'),
    path('pl/<int:production_id>/modify/', views.pl_modify, name='pl_mdf'),
    path('pl/<int:production_id>/delete/', views.pl_delete, name='pl_del'),
    path('mw/<int:material_id>/', views.edit_mt, name='mt_edit'),
    path('mw/<int:material_id>/modify/', views.mt_modify, name='mt_mdf'),
    path('mw/<int:material_id>/delete/', views.mt_delete, name='mt_del'),
    path('fpw/<int:finished_id>/', views.edit_fp, name='fp_edit'),
    path('fpw/<int:finished_id>/modify/', views.fp_modify, name='fp_mdf'),
    path('fpw/<int:finished_id>/delete/', views.fp_delete, name='fp_del'),
    path('dir/<int:direction_id>/', views.edit_dir, name='dir_edit'),
    path('dir/<int:direction_id>/modify/', views.dir_modify, name='dir_mdf'),
    path('dir/<int:direction_id>/delete/', views.dir_delete, name='dir_del'),
    path('mwout/<int:material2_id>/', views.edit_mtout, name='mt_edit2'),
    path('mwout/<int:material2_id>/modify/', views.mtout_modify, name='mtout_mdf'),
    path('mwout/<int:material2_id>/delete/', views.mtout_delete, name='mtout_del'),
    path('rest5/', views.materialout_list),
    path('plout/<int:production2_id>/', views.edit_plout, name='pl_edit2'),
    path('plout/<int:production2_id>/modify/', views.plout_modify, name='plout_mdf'),
    path('plout/<int:production2_id>/delete/', views.plout_delete, name='plout_del'),
    path('rest6/', views.productionout_list),
    path('fwout/<int:finished2_id>/', views.edit_fwout, name='fw_edit2'),
    path('fwout/<int:finished2_id>/modify/', views.fwout_modify, name='fwout_mdf'),
    path('fwout/<int:finished2_id>/delete/', views.fwout_delete, name='fwout_del'),
    path('rest7/', views.finishedout_list),
]